#!/usr/bin/perl
$|=1;

our $VERSION = '3.0.0';

use v5.12;
use utf8;
use autodie;
use Carp;

use File::Spec;
use FindBin qw/$Bin/;
use lib File::Spec->catfile($Bin, 'lib'), $Bin;
binmode(STDOUT, ":utf8");

#-----------------------------------------------------------------------------
use Coro;
use AnyEvent;
use Coro::Timer;
use Getopt::Long qw/:config bundling/;
use POSIX        qw/strftime/;
use List::Util   qw/reduce/;
use File::Basename;
#-----------------------------------------------------------------------------
use PCW::Core::Utils qw/get_proxylist readfile/;
use PCW::Core::Data;
use PCW::Core::DesuLog;
use PCW::Core::OCR;

#-----------------------------------------------------------------------------
# Global variables
#-----------------------------------------------------------------------------
our $mode_config;   #-- modes/*
our $common_config; #-- config.pl
our $chan_config;   #-- chans/*

my %data = (
            proxies => [],      #-- list of proxies
            agents  => [],      #-- list of user-agents
            engine  => 0,       #-- PCW::Engine::* object
            logging => 0,       #-- PCW::Core::DesuLog object
           );

#-----------------------------------------------------------------------------
# Config
#-----------------------------------------------------------------------------
my %arguments = (
    chan       => '',
    mode       => '',
    verbose    => 0,
    useragents => File::Spec->catfile('.', 'UserAgents'),
    proxy_file => File::Spec->catfile('.', 'proxy', 'no'),
    proxy_type => 'http',

    common_config => File::Spec->catfile('.', 'config.pl'), #-- common config path
    mode_config   => '',                                     #-- mode config path

    loglevel   => 1,
    logfile    => '',
    lognocolor => undef,
);

#-----------------------------------------------------------------------------
#-----------------------------------------------------------------------------
sub parse_args
{
    my $help   = 0;
    my $desu   = 0;
    my $result = GetOptions(
                            'chan=s'     => \$arguments{chan},
                            'mode=s'     => \$arguments{mode},
                            'proxy=s'    => \$arguments{proxy_file},
                            'ua=s'       => \$arguments{useragents},
                            'cconfig=s'  => \$arguments{common_config},
                            'mconfig=s'  => \$arguments{mode_config},
                            'loglevel=i' => \$arguments{loglevel},
                            'logfile=s'  => \$arguments{logfile},
                            'lognocolor' => \$arguments{lognocolor},
                            'verbose'    => \$arguments{verbose},
                            'help|?'     => \$help,
                            'desu'       => \$desu,
                           );
    if ($desu)
    {
        desu();
        exit 1;
    }
    if ($help || !($arguments{mode} && $arguments{chan}))
    {
        usage();
        exit 1;
    }
    $arguments{mode_config} = File::Spec->catfile('.', 'modes', "$arguments{mode}.pl")
        unless $arguments{mode_config};
}


#-----------------------------------------------------------------------------
# Info
#-----------------------------------------------------------------------------
sub show_info()
{
    say "Perl Chan Wiper v$VERSION";
    say "~" x 30;
    say sprintf "Chan: %s %s", $arguments{chan}, ($chan_config->{description} ? "($chan_config->{description})" : "");
    say "Engine: "          . $chan_config->{engine};
    say "Work mode: "       . $arguments{mode};
    say "Mode config: "     . $arguments{mode_config};
    say "Common config: "   . $arguments{common_config};
    say "Proxies loaded: "  . scalar @{ $data{proxies} };
    say "Browsers loaded: " . scalar @{ $data{agents} };
    say "~" x 30;
    say "Log level: ".       $arguments{loglevel};
    say "Log file: ".        ($arguments{logfile}   || "STDOUT");
    say "Colored logging: ". ($arguments{lognocolor} ? 'no'  : 'yes');
    say "Verbose output: " . ($arguments{verbose}    ? 'yes' : 'no');
    say "~" x 30;
}

#-----------------------------------------------------------------------------
# Load
#-----------------------------------------------------------------------------
sub load_configs()
{
    require $arguments{common_config} || die; #-- load $common_config
    require $arguments{mode_config}   || die; #-- load $mode_config
}

sub load_proxies()
{
    my @proxies    = get_proxylist($arguments{proxy_file}, $arguments{proxy_type});
    $data{proxies} = \@proxies;
}

sub load_agents()
{
    my @agents = readfile($arguments{useragents});
    $data{agents} = \@agents;
}

sub load_chan()
{
    my $package = File::Spec->catfile('.', 'chans', "$arguments{chan}.pl");
    require "$package"; #-- load $chan_config
}

sub load_logging()
{
    $data{logging} = PCW::Core::DesuLog->new( file     => $arguments{logfile},
                                              level    => $arguments{loglevel},
                                              colored  => !$arguments{lognocolor},
                                              settings => $common_config->{log_settings} );
}

sub load_engine()
{
    my $package = "PCW::Engine::". $chan_config->{engine};
    eval("use $package");
    Carp::croak($@) if $@;
    $data{engine} = $package->new(chan_config   => $chan_config,
                                  common_config => $common_config,
                                  agents        => $data{agents},
                                  log           => $data{logging},
                                  verbose       => $arguments{verbose},
                                  data => PCW::Core::Data->new(),
                                  ocr  => PCW::Core::OCR->new(log => $data{logging}, config => $common_config->{captcha_decode}) );
}

sub load_mode()
{
    my $package = "PCW::Modes::$arguments{mode}";
    eval("use $package");
    Carp::croak($@) if $@;
    return $package->new(engine      => $data{engine},
                         proxies     => $data{proxies},
                         mode_config => $mode_config,
                         log         => $data{logging},
                         verbose     => $arguments{verbose});

}

sub load_all()
{
    load_configs();
    load_proxies();
    load_agents();
    load_chan();
    load_logging();
    load_engine();
    return load_mode();
}

#-----------------------------------------------------------------------------
# Usage
#-----------------------------------------------------------------------------
sub desu()
{
    print $_ while (<DATA>);
}

sub usage()
{
    my @modes;
    for my $path (glob "PCW/Modes/*.pm")
    {
        next if $path =~ /Base/;
        my ($mode, undef, undef) = fileparse($path, '.pm');
        push @modes, $mode;
    }
    my @chans;
    for my $path (glob "chans/*.pl")
    {
        next if $path =~ /example/;
        my ($chan, undef, undef) = fileparse($path, '.pl');
        push @chans, $chan;
    }
    my @engines;
    for my $path (glob "PCW/Engine/*.pm")
    {
        next if $path =~ /Abstract|Simple/;
        my ($engine, undef, undef) = fileparse($path, '.pm');
        push @engines, $engine;
    }

    local $" = ', ';
    print <<DESU
PerlChanWiper - a multifunction CLI tool for some imageboards

Usage: $0 --chan [chan] --mode [mode] ...

PCW Options:
    --chan          Chan name (@chans)
    --mode          Work mode (@modes)
    --proxy         Path to file or url which contains proxies (default is '$arguments{proxy_file}')
    --proxytype     Default proxy protocol (default is '$arguments{proxy_type}')
    --ua            User agents list file (default is '$arguments{useragents}')
    --cconfig       Common config file (default is '$arguments{common_config}')
    --mconfig       Mode config file (default is 'modes/\$mode_name.pl')

    --logfile       File for logging (STDOUT by default)
    --lognocolor    Disable colored log output
    --loglevel      1-4, 1 by default
    --verbose       Verbose output

UI options:
    --help          Show this message and exit
    --desu          Show desu and exit

Supported chan engines: @engines
Version $VERSION
DESU
}

#-----------------------------------------------------------------------------
# MAIN CODE
#-----------------------------------------------------------------------------
parse_args();
my $pcw = load_all();
show_info();

#-----------------------------------------------------------------------------
# RUN
#-----------------------------------------------------------------------------
my $start_time = time;
my $ws = AnyEvent->signal(signal => "INT", cb => sub { $pcw->stop; });
$pcw->init;
$pcw->start;
while ($pcw->{is_running})
{
    Coro::Timer::sleep 1
}

#-----------------------------------------------------------------------------
# ON EXIT
#-----------------------------------------------------------------------------
sub show_stats
{
    my %stats = %{ shift() };
    say "~" x 30;
    for my $k (keys %stats)
    {
        say ucfirst($k =~ s/_/ /gr) .": $stats{$k}";
    }
}

given ($arguments{mode})
{
    # when ('ProxyChecker')
    # {
    #     show_stats $pcw->{stats};
    #     my @p = @{ $pcw->{checked} };
    #     say $mode_config->{save} ? sprintf("There are %d good proxies.", scalar @p) : "Good proxies: @p";
    # }
    # when ('AutoBump')
    # {
    #     show_stats $pcw->{stats}{bump};
    #     show_stats $pcw->{stats}{delete};
    # }
    default
    {
        show_stats $pcw->{stats};
    }
}

__DATA__
KMMW;  lMMMMK   XMl       ;Mc0M0 xMM,M:OMMMMK xMMxcMMMMMMMMMMMkWMMMMMMMMMMk     .WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
0MWx.  dMMMMO.  xO'        xW,WMd dMN:M''WMMMM..WMW.,XMMMMMMMMMWONMMMMMMMMMMk     .XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
Mx.  ;XMMMWc   '.          WoxMM' dMOdN  lMMMMd dMMO  oWMMNMMMMMM0XMMMMMMMMMMX.     OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
.  .OMMMMO.               cX:MMN. kMcNx   kMMMW. NMM:  .0MNoXMMMMMKXMMMM0KMMMMW,     dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  ;XMMMN:             :   XcXMM0  KNlM,    KMMMk :MMN.,. cWN'kMMMMMKKMMMMxcWMMMW,     lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
;cNMMMx.            .k   ckOMMNd .MdXW.    .NMMM; KMMk Ol .0K oMMMMMKXMMMMk.0MMMW,     lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
XMMM0.  ..         lX.  .0xMMWW. :NxMNx     'WMMN.'MMMl X0. lo ,WMMMM0NMMMMk oMKWW.     lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMX;  :x'        .KN.   xkMMWW0  OOWWWW.     ,WMMK xMMMc.NWl .  .XMMMMOWMMMMx ;X,NX.     xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
X: 'xNo        .xWW,   :KMMWWM, .WNMNMWd      ;WMM0.NMMMl;MMK.   'KMMMWOMMMMMl ;c.Nk      0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
'oXMk.        oWMW;   .NMMMNMk  kMMWWWMM'      ,WMX0:MMMMkdNMWd  d;0MMMXKMMMMM, . 'W,     .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMk.       .oNWMM:   .XMMMWWW. ,MMMNWMMMX       .NdkKxMMMMNd,XMWo.Nc0MMMOWMMMMN.   ox      ;MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
k.       .dWMMMM:    0MMMNWMo  XMMNWMMMMMO       .O,oNNMMMMW  OMMWWMoKMMWOMMMMMx    ,'      OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
       'kWMMMMW;    OMMWNMMK  xMMWWMMMMMMMd        :.:WMMMMMc  oMMMMMxXMMOWMMMMM'    ;      .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    .cKMMMMMMN'    OMMNNMMW. :MMNNMMMMMMMMMo .l       .XMMMMK   :MMMMMkWMNOMMMMM0    ;       xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
  ,kWMMMMMMMX.    OMMNWWXMc 'WMWXMMMMMMMMMMMo .0'       kMMMM.   ;WMMMMXMMOMMMMMM, , ,       'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
oNMMMMMMMMMO     OMWXMMMNc  oxOxKNWMMMMMMMMMMd ,Wx       :NMMl    :MMMMMKMOKMMMMMk d;,.       XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMo    .KMNWMMMM0 .XMXkOkdoolcc:;;coxOd ,WNc      .xM0     cMMMM;WN.WMMMMW OKc.       dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMN'    'NWNMMMMMK .XMWXMMMMMMMMMMMNKOxl:'..lxk;      .O      oMMM.kM.dMMMMM:WM:        :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMO.    :NNWMMMMMK..XMWXMMMMMMMMMMMMMMMMMMMMo ldl;.             OMM':M,,MMMMMXMM:        ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMN:     dNWMMMMMM0 'NMWNMMMMMMMMMMMMMMMMMMMMMMK,lWMMO.            XM'.M;.MMMMMMMM,        ;MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMk.    .0WMMMMMMMO cWMWNMMMMMMMMMMMMMMMMMMMMMMMMMk,OMMMk.          'M. N,.MMMMMMMM.        cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMK'     lNMMMMMMMMx xMMNWMMMMMMWNNN0kOOO00KXWMMMMMMMWdc0MMWo          o  O..MMMMMMM0         kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
X:    'xWMMMMMMMMWc.KMWNWMMMMMMNXXKXNMMMMMMMMWMMMMMMMMMWkokWMX;           c ,MMMMMMM,         WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
   .oXMMMMMMMMMMX.:WMNNMMMMMMMMMX0kdlc;;,,,,,;:codOKWMMMMMXdd0MO.           lMMMMMMk         .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
.oKMMMMMMMMMMMMk.OMWNWMMMMMMMXO,  ..                ..':okKNMKxkO,          OMMMMMX.          NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMN::NMNNMMMMMMMMM0;lOWk .....           ,WXko;.  .';:lx.        WMMMMW'           dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMk,0MNNMMMMMMMMMMMWMMMWdNMMMMMO           oMMMMM,   :OMMW       :MMMMW,            'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMX;oWNNMMMMMMMMMMMMMMMMMKOMMW0o'       .    'MMMMd 'kWMMMMM.      0MMMM;              KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMWl:XNNWMMMMMMMMMMMMMMMMMMW... ..      .lMW.  lMMWl:KMMMMMMMM,     ,MMMW;               :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMx;0NNMMMMMMMMMMMMMMMMMMMMMMc   ON;   .cNO.0c .NMWONMMMMMMMMMW;     0MMN'                 XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMO;dNWMMMMMMMMMMMMMMMMMMMMMMMMW'.K0MMMWMMMNxKN. KMMWMMMMMMMMMMMW,    :MMK.       .          :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMO'cXWMMMMMMMMMMMMMMMMMMMMMMMMMMMW: :kXMMMMMMXo..KMMMMMMMMMMMMMMMM.   .NMo        ; .x         XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WkldNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdoolool;,. .l0KWMMMMMMMMMMMMMW:    OX'       .: .kc         :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMX'    do        c; xdK           KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo     ,.       .x.;NKx:           'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0.             .do'0MWoO             oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;              o0:kMMMoN.              XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:             .dKkkMMMMdNl               'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMO0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;             ;OWXXMMMMMxKW                 lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.            ,xWMMMMMMMMMM0kO.                 OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,            :0WMMMMMMMMMMMMMKxM'                 .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMNKOd0MMMMMMMMMMMMMMMMMMMMMKo'              ,MMMMMMM0oNMMMMMMOOM.                  'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMW:kkxxkkkkOOOOOOO000Xk;NMMMMMMMMMMMMMMMMMMMWOddddxxOK0       ;xMMMMMMWoO0MMMMMMdNN                    cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMXdKkWMMMMMMMMKOxWW0loWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.      .dNMMMMMMO0xXMMMMMMoMl                     xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMoxKMMMMMMMMWMW0llXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:        xoMMMMMKMdNoMMMMMMk00                       KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMM0d0NWMMMMWX0dd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;          0oMMMMMdkOo0kxOMMXxK                        .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMX0OOOOOO0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.            koWO0000XMMWO0NMNdMo                         'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'               coW0000KWMMxxkd0NdWo                          cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'                  .kKMMNOdOlxoNMMMKcN:                           dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc.                      NdMMKKMdKdX0MMMxXM.                            0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o'                          NdMMMMMo0OMMMMMoMK                             .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,                             'oWMMMMMxoWMMMMKxM:                              'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
KKNMMMMMMMMMMMMMMMMMMMMMMWXX0:clx0Kx'                         ,KMMMMMMMMMMMMMoWX                                lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMNKKKKWMMMMMMMMMMMMMNXXXXMMkNMMMMMMM0;                       cWMMMMMMMMMMMM0xW'                                 OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMXKKKKNMMWN000KNMMMMMMxMMMMMMMMMMXc                     x0MMMMMMMMMMMX;0:                                  .NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMX000KWMMMMMMMMMWxMKMMMMMMMMMMWo.                  0oMMMMMMMMMMMKdk                                    lMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMXkXoMMMMMMMMMMMMMk'                ok0MMMMMMMMMMWoO                                     XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMM0x'NMMMMMMMMMMMMMMMK:              .NoWMMMMMMMMMXxk                                     :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMM0 xMMMMMMMMMMMMMMMMMMWd.            ,NoMM0XMMMMMxKo                                      XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMW.,MMMMMMMMMMMMMMMMMMMMMMO.           oOkKdoMMMMMoM,                                      xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
