#!/usr/bin/perl -w
$|=1;

use v5.12;
use utf8;

use autodie;
use WWW::ProxyChecker;
use List::MoreUtils qw/uniq/;

die "Usage: $0 [proxylist] [checked proxylist]"
    if @ARGV != 2;

my @raw_proxies;
my ($proxy_list, $checked_proxy_list) = @ARGV;
my $raw_proxies;

open my $fh, "<", $proxy_list;
{
    local $/ = undef;
    $raw_proxies = <$fh>;
    close $fh;
}

push @raw_proxies, $1
    while $raw_proxies =~ /((http|socks4?:\/\/)?      #-- protocol
                               ((\w|\d)+:(\w|\d)+@)?     #-- user login and password
                               (\d+\.\d+\.\d+.\d+\:\d+)| #-- e.g., 192.168.1.1:80
                               ((\w|\d|\.)+\.\w+:\d+)    #-- e.g., my.awesome.proxy.com:80
                           )/gsx;

my @proxies;
# for my $type ('http', 'socks', 'socks4')
for my $type ('http')
{
    for (@raw_proxies)
    {
        if (/http|socks/)
        {
            push @proxies, $_;
        }
        else
        {
            push @proxies, "$type://$_";
        }
    }
}
@proxies = uniq @proxies;

my $checker = WWW::ProxyChecker->new( debug         => 1,
                                      agent         => 'Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1.12)',
                                      check_sites   => [ "http://google.com" ],
                                    );
my $working_ref= $checker->check(\@proxies);

die "No working proxies were found\n"
    if not @$working_ref;

open $fh, ">", $checked_proxy_list;
print $fh "$_\n"
    for @$working_ref;
close $fh;
